// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARS2DLD23rUEQ0unHc7gWyuVbduSO06d8',
    appId: '1:553242494396:web:5b88f5f3d94a335f2517b9',
    messagingSenderId: '553242494396',
    projectId: 'barbershop-toni',
    authDomain: 'barbershop-toni.firebaseapp.com',
    storageBucket: 'barbershop-toni.firebasestorage.app',
    measurementId: 'G-64KFM6H7N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKNw5eCjisT_1fFX0KeNd26ABdiNA1W0',
    appId: '1:553242494396:android:0afbeff38ca28cbe2517b9',
    messagingSenderId: '553242494396',
    projectId: 'barbershop-toni',
    storageBucket: 'barbershop-toni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSK0fp2IBBn-iHq_rUsKId6Z3vrjY6NpU',
    appId: '1:553242494396:ios:e719a67fb7b453a12517b9',
    messagingSenderId: '553242494396',
    projectId: 'barbershop-toni',
    storageBucket: 'barbershop-toni.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSK0fp2IBBn-iHq_rUsKId6Z3vrjY6NpU',
    appId: '1:553242494396:ios:e719a67fb7b453a12517b9',
    messagingSenderId: '553242494396',
    projectId: 'barbershop-toni',
    storageBucket: 'barbershop-toni.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARS2DLD23rUEQ0unHc7gWyuVbduSO06d8',
    appId: '1:553242494396:web:3df470870255b9a12517b9',
    messagingSenderId: '553242494396',
    projectId: 'barbershop-toni',
    authDomain: 'barbershop-toni.firebaseapp.com',
    storageBucket: 'barbershop-toni.firebasestorage.app',
    measurementId: 'G-QLDBRM76B3',
  );
}
